base_to_footprint_ekf:
  ros__parameters:
    frequency: 50.0
    publish_tf: true
    transform_timeout: 0.01
    transform_time_offset: 0.045
    two_d_mode: false

    #x     , y     , z,
    #roll  , pitch , yaw,
    #vx    , vy    , vz,
    #vroll , vpitch, vyaw,
    #ax    , ay    , az

    pose0: base_to_footprint_pose
    pose0_config: [true,  true,  true,
                   true,  true,  true,
                   false, false, false,  # Linear velocities
                   true, true, true,     # Angular velocities
                   false, false, false]  # Acceleration

    imu0_frame: imu_link
    imu0_config: [false, false, false,
                  false, false, false,
                  false, false, false,  # Linear velocities
                  true, true, true,     # Angular velocities(vroll, vpitch, vyaw)
                  false, false, false]  # Linear Acceleration

    odom_frame: base_footprint
    world_frame: base_footprint
