footprint_to_odom_ekf:
  ros__parameters:
    frequency: 50.0
    publish_tf: true
    transform_timeout: 0.01
    two_d_mode: true

    #x     , y     , z,
    #roll  , pitch , yaw,
    #vx    , vy    , vz,
    #vroll , vpitch, vyaw,
    #ax    , ay    , az

    odom0: odom/raw
    odom0_config: [false, false, false,
                   false, false, false,
                   true,  true,  false,  # Линейные скорости x, y
                   false, false, true,   # Угловая скорость по yaw
                   false, false, false]  # Ускорения

    imu0_frame: imu_link
    imu0_config: [false, false, false,
                  false, false, true,   # Use yaw
                  false, false, false,  # Линейные скорости отключены
                  false, false, true,   # Угловая скорость по yaw
                  false, false, false]  # Ускорения отключены

    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom
